# RaidHelper Plugin Config

settings:
  message: "Ring the bell to spawn raiders above it if they're not found."
  bell_cooldown: 10    # Ticks before bell can be used again.
  bell_work_after: 60 # Ticks before bell can be used since the start of a wave.
  height: 10          # Spawn height above the bell.
  radius: 50          # Effect radius of the bell.
  delay: 60           # Delay in ticks before raiders teleport.

  raid_check:
    mode: SCHEDULER        # 'SCHEDULER' for periodic checks, 'EVENT' for event-driven.
    world_frequency: 100   # Ticks between world raid checks. If mode is scheduler only.
    max_checks_per_tick: 5 # For world checks, how many raids within worlds per tick may be processed.
    raid_frequency: 20     # Ticks between individual raid checks.

  worlds:
    - world
    # - world_nether
    # - world_the_end