# RaidHelper Plugin Configuration

settings:
  messages:
    teleport: "Raiders on their way to your bell!"
    ring: "If you can't find the raiders, just ring the bell."
    cooldown: "Please wait before ringing the bell again."
    some_cooldown: "Some raids are in cooldown, but others have teleported raiders."

  mechanics:
    bell_cooldown: 100          # Ticks before the bell can be used again
    bell_work_delay: 60         # Ticks before the bell works since the start of a wave
    teleport_delay: 60          # Delay in ticks before raiders teleport
    spawn_height: 10            # Height above the bell where raiders spawn
    effect_radius: 50           # Radius of the bell's effect

  raid_check:
    mode: SCHEDULER             # 'SCHEDULER' for periodic checks, 'EVENT' for event-driven
    world_frequency: 100        # Ticks between world raid checks (scheduler mode only)
    max_checks_per_tick: 5      # Max raids to process per tick
    max_pool_size: 5            # Maximum size of the teleporter pool

  worlds:
    - world                     # Add other worlds as needed (e.g., custom_world, world_the_end)
