name: raidhelper
version: '1.0'
main: ru.ephy.raidhelper.Raidhelper
api-version: '1.20'

author: ephy
description: >
  Makes fights with raiders much more comfortable. If you cannot find 
  the last raiders, ring a bell and they will spawn above it. 
  Several configurations are available to customize the plugin 
  to your needs.

source: https://github.com/ephyrriz/RaidHelper
